name: Auto-build HTML files

on:
  push:
    branches:
      - working
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Load repository
        uses: actions/checkout@v2
      - name: Switch to the master branch (or create it if it doesn't exist)
        run: |
          git checkout -B master
      - name: Reset master to point to working's HEAD
        run: |
          git fetch --all --no-tags
          git reset --hard origin/working
          git status
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pull in comic_git_engine
        run: |
          git submodule add -f https://github.com/ryanvilbrandt/comic_git_engine
      - name: Run build_site.sh
        run: |
          sudo ./comic_git_engine/scripts/build_site.sh
