name: Auto-build HTML files

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # 1) Build the arbitrary env blob here (secrets allowed in a normal job)
  prep-env:
    runs-on: ubuntu-latest
    outputs:
      env_blob: ${{ steps.collect.outputs.env_blob }}
    steps:
      - id: collect
        name: Compose env lines (including secrets)
        env:
          # 👇 Put anything you want here; secrets are allowed in env:
          API_TOKEN: ${{ secrets.MY_ENV_VAR1 }}
          GH_PAT: ${{ secrets.MY_ENV_VAR2 }}
        run: |
          {
            echo "MY_ENV_VAR1=$MY_ENV_VAR1"
            echo "MY_ENV_VAR2=$MY_ENV_VAR2"
          } > env.txt

          # Expose as a multi-line step output
          {
            echo "env_blob<<EOF"
            cat env.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  # 2) Call your reusable workflow and feed it the prepared blob
  call-build-site:
    needs: prep-env
    uses: comic-git/comic_git_engine/.github/workflows/build_site.yaml@v1
    secrets: inherit     # pass secrets context through to the called workflow if it needs it
    with:
      env: ${{ needs.prep-env.outputs.env_blob }}
