name: Auto-build HTML files

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-build-site:
    uses: ./.github/workflows/build_site.yaml
    with:
      env_kv: |
        SITE_ENV=production
        ENGINE_VERSION=v1
        # Any secret you choose, no need to predeclare in callee:
        API_TOKEN=${{ secrets.MY_API_TOKEN }}
        GH_PAT=${{ secrets.GH_PAT }}
        # You can add/remove lines freely
        EXTRA_FLAGS=--delete-scheduled-posts
    secrets: inherit
